### ISSUE TITLE
[Bug Report] JS/TS SDK 타입 에러

### ISSUE THREAD

**Issue by rojiwon123** [portone-io/server-sdk#34]
# 문제 상황

라이브러리에서 제공하는 일부 타입정보가 적절하게 바인딩되지 못하는 문제가 있습니다.

# 예상되는 원인

dist/generated/payment/Payment.d.ts 파일을 확인해본 결과 import 하고있는 타입들의 경로가 잘못 변환되어있습니다.
아마도 빌드과정에서 제대로 번들링이 되지 않은 것 같습니다.

# 재현 가능한 예제

v0.6.1 `@portone/server-sdk`를 설치하고 아래의 코드를 작성하면 `res` 변수가 `any`로 인식됩니다.

```ts
import { PortOneClient } from "@portone/server-sdk";

const client = PortOneClient("", { storeId: "" })
    .payment.getPayment("")
    .then((res) => res);
```

**Comment by rojiwon123** [comment]
v0.2.1 에서 v0.6.2 버전으로 업그레이드하는 과정에서 발견했습니다. v0.3.0부터 일부 파일의 경로가 `#generated/*`로 alias되어있는데, 의도된건가요? 제 개발 환경에서는 이 부분 때문에 타입 연산이 제대로 동작하지 않습니다.

**Comment by kiwiyou** [comment]
안녕하세요, 이슈 제보헤 주셔서 감사합니다. 해당 사항 현재 인지하여 버그가 수정된 버전을 릴리스 준비중입니다.

**Comment by kiwiyou** [comment]
@rojiwon123 0.6.2 버전에서 해당 문제 해결됨을 확인했습니다.
